### ISSUE TITLE
Resolve `ember-cli-babel` deprecation

### ISSUE THREAD

**Issue by rmachielse** [bmac/ember-cli-content-for-config#2]
This addon seems outdated, is there any chance a pr to upgrade it's dependencies gets merged?
Or am I missing out on a new solution for this?

**Comment by joe-wroten-q2** [comment]
I'm seeing the same.

**Comment by rmachielse** [comment]
@bmac any thoughts on this?

**Comment by bmac** [comment]
@rmachielse I'd be happy to merge a pr to fix the issue if you have the time to create one.
